### PR TITLE
Create Issue #2 and #4

### PR DESCRIPTION
**Pull request by minjung1004**
Created Issue #2 and #4. (house listing and navbar).

### CODE REVIEW

**Review by larinachen — APPROVED** [review]
Looks good! The only thing I'm not sure about are the target/classes/META-INF/resources/index.html and target/classes/META-INF/resources/style.css. I'm assuming they are auto-generated - in that case, the PR looks good. Otherwise, I'm not sure what these 2 files do. Maybe @nnooney can double click on this?

**Comment by nnooney** [comment]
It looks like `target/` should be excluded from the gitignore file. We can revert them with `git rm` and pushing changes to the setup branch. Let's also add a `.gitignore` file to this PR with the following contents:

```
.classpath
.idea
.project
.settings/
target/
```

I pulled this from the SPS repo. That way, these auto-generated files won't be checked in to source. For more information, I found this StackOverflow post: https://stackoverflow.com/questions/70216/whats-the-purpose-of-meta-inf.

**Review by nnooney — CHANGES_REQUESTED** [review]
Requesting to remove files under target/ and adding a gitignore.

**Comment by minjung1004** [comment]
Removed files under target and added a .gitignore

**Review by nnooney — APPROVED** [review]
LGTM

**Pull request merged**
